### ISSUE TITLE
[improvement] A remaining comma in .json file break the loop

### ISSUE THREAD

**Issue by leo-smi** [tmetsch/pytkgen#14]
Acctually the error occurs because json library (extra comma after ```"columnspan":3,```):

```
{
    "LabelFrame":{
        "text":"(0, 0, 3)",
        "row":0,
        "column":0,
        "weight":1,
        "columnspan":3,
    }
}
```

The working .json is:
```
{
    "LabelFrame":{
        "text":"(0, 0, 3)",
        "row":0,
        "column":0,
        "weight":1,
        "columnspan":3
    }
}

```

The main .py is:
```
import tkgen.gengui

if __name__ == '__main__':
    root = tkgen.gengui.TkJson(
            'ex02.json',
            title = 'Some test gui...'
    )

    root.mainloop()
```
The error:

```
Traceback (most recent call last):
  File "C:\Users\leand\OneDrive\Documentos\MEGA - Python\Tkinter\PyTKGen\Projetos\2\ex02.py", line 4, in <module>
    root = tkgen.gengui.TkJson(
  File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\site-packages\tkgen\gengui.py", line 457, in __init__
    super(TkJson, self).__init__(filename, title, prefer_tk,
  File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\site-packages\tkgen\gengui.py", line 97, in __init__
    user_interface = json.load(open(filename)) if os.path.isfile(
  File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 5 (char 134)
```

**Comment by tmetsch** [comment]
Yeah, that looks correct to me; There is no comma after the last element. The JSON spec does not define that :-) Have a look [here](https://www.json.org/json-en.html).

**Comment by leo-smi** [comment]
> Yeah, that looks correct to me; There is no comma after the last element. The JSON spec does not define that :-) Have a look [here](https://www.json.org/json-en.html).

Thank you!
